# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: '000'

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Research', url: 'research.html'}
- {name: 'Publications', url: 'publications.html'}
- {name: 'Outreach', url: 'outreach.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter',    link: 'https://twitter.com/JaceKuske'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/jace-kuske/'}


# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
